// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skillmgr} from '../models';

export function AddRepository(arg1:string):Promise<skillmgr.Inventory>;

export function AddSource(arg1:string):Promise<skillmgr.Inventory>;

export function AdoptCurrentEnabledSkills():Promise<skillmgr.AdoptSyncResult>;

export function ApplySync():Promise<skillmgr.ApplySyncResult>;

export function BrowseForSource():Promise<string>;

export function BrowseForSyncFolder():Promise<string>;

export function BrowseForTarget():Promise<string>;

export function CloneRepository(arg1:string,arg2:string,arg3:string,arg4:string):Promise<skillmgr.CloneRepositoryResult>;

export function DisableSkill(arg1:string):Promise<skillmgr.Inventory>;

export function EnableSkill(arg1:string):Promise<skillmgr.Inventory>;

export function EnableSkillLocalOnly(arg1:string):Promise<skillmgr.Inventory>;

export function GenerateSkillProfile(arg1:string,arg2:boolean):Promise<skillmgr.SkillProfileResult>;

export function GetDebugLogPath():Promise<string>;

export function GetInventory():Promise<skillmgr.Inventory>;

export function ListSkillFiles(arg1:string,arg2:string):Promise<Array<skillmgr.SkillFileEntry>>;

export function OpenInVSCode(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function PullRepository(arg1:string):Promise<skillmgr.PullSourceResult>;

export function PullSource(arg1:string):Promise<skillmgr.PullSourceResult>;

export function ReadSkillEnvFile(arg1:string):Promise<string>;

export function RemoveRepository(arg1:string):Promise<skillmgr.Inventory>;

export function RemoveSkillFromSync(arg1:string):Promise<skillmgr.Inventory>;

export function RemoveSource(arg1:string):Promise<skillmgr.Inventory>;

export function RenameRepository(arg1:string,arg2:string):Promise<skillmgr.Inventory>;

export function RenameSource(arg1:string,arg2:string):Promise<skillmgr.Inventory>;

export function RescanAll():Promise<skillmgr.Inventory>;

export function ResolveConflict(arg1:string):Promise<skillmgr.Inventory>;

export function SaveConfig(arg1:skillmgr.Config):Promise<skillmgr.Inventory>;

export function SaveLLMConfig(arg1:skillmgr.SyncLLMConfig):Promise<skillmgr.Inventory>;

export function SaveSkillEnvFile(arg1:string,arg2:string):Promise<skillmgr.Inventory>;

export function SaveSkillTags(arg1:string,arg2:Array<string>):Promise<skillmgr.Inventory>;
