// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSource(arg1) {
  return window['go']['main']['App']['AddSource'](arg1);
}

export function BrowseForSource() {
  return window['go']['main']['App']['BrowseForSource']();
}

export function BrowseForTarget() {
  return window['go']['main']['App']['BrowseForTarget']();
}

export function DisableSkill(arg1) {
  return window['go']['main']['App']['DisableSkill'](arg1);
}

export function EnableSkill(arg1) {
  return window['go']['main']['App']['EnableSkill'](arg1);
}

export function GetInventory() {
  return window['go']['main']['App']['GetInventory']();
}

export function OpenInVSCode(arg1) {
  return window['go']['main']['App']['OpenInVSCode'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function ReadSkillEnvFile(arg1) {
  return window['go']['main']['App']['ReadSkillEnvFile'](arg1);
}

export function RemoveSource(arg1) {
  return window['go']['main']['App']['RemoveSource'](arg1);
}

export function RenameSource(arg1, arg2) {
  return window['go']['main']['App']['RenameSource'](arg1, arg2);
}

export function RescanAll() {
  return window['go']['main']['App']['RescanAll']();
}

export function ResolveConflict(arg1) {
  return window['go']['main']['App']['ResolveConflict'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveSkillEnvFile(arg1, arg2) {
  return window['go']['main']['App']['SaveSkillEnvFile'](arg1, arg2);
}
