// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skillmgr} from '../models';

export function AddSource(arg1:string):Promise<skillmgr.Inventory>;

export function BrowseForSource():Promise<string>;

export function BrowseForTarget():Promise<string>;

export function DisableSkill(arg1:string):Promise<skillmgr.Inventory>;

export function EnableSkill(arg1:string):Promise<skillmgr.Inventory>;

export function GetInventory():Promise<skillmgr.Inventory>;

export function OpenInVSCode(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function PullSource(arg1:string):Promise<skillmgr.PullSourceResult>;

export function ReadSkillEnvFile(arg1:string):Promise<string>;

export function RemoveSource(arg1:string):Promise<skillmgr.Inventory>;

export function RenameSource(arg1:string,arg2:string):Promise<skillmgr.Inventory>;

export function RescanAll():Promise<skillmgr.Inventory>;

export function ResolveConflict(arg1:string):Promise<skillmgr.Inventory>;

export function SaveConfig(arg1:skillmgr.Config):Promise<skillmgr.Inventory>;

export function SaveSkillEnvFile(arg1:string,arg2:string):Promise<skillmgr.Inventory>;
