// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepository(arg1) {
  return window['go']['main']['App']['AddRepository'](arg1);
}

export function AddSkillTags(arg1, arg2) {
  return window['go']['main']['App']['AddSkillTags'](arg1, arg2);
}

export function AddSource(arg1) {
  return window['go']['main']['App']['AddSource'](arg1);
}

export function BrowseForCloneParent() {
  return window['go']['main']['App']['BrowseForCloneParent']();
}

export function BrowseForExistingRepository() {
  return window['go']['main']['App']['BrowseForExistingRepository']();
}

export function BrowseForSource() {
  return window['go']['main']['App']['BrowseForSource']();
}

export function BrowseForSyncFolder() {
  return window['go']['main']['App']['BrowseForSyncFolder']();
}

export function BrowseForTarget() {
  return window['go']['main']['App']['BrowseForTarget']();
}

export function CloneRepository(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CloneRepository'](arg1, arg2, arg3, arg4);
}

export function DisableSkill(arg1) {
  return window['go']['main']['App']['DisableSkill'](arg1);
}

export function DisableSkills(arg1) {
  return window['go']['main']['App']['DisableSkills'](arg1);
}

export function EnableSkill(arg1) {
  return window['go']['main']['App']['EnableSkill'](arg1);
}

export function EnableSkills(arg1) {
  return window['go']['main']['App']['EnableSkills'](arg1);
}

export function GenerateSkillProfile(arg1, arg2) {
  return window['go']['main']['App']['GenerateSkillProfile'](arg1, arg2);
}

export function GetDebugLogPath() {
  return window['go']['main']['App']['GetDebugLogPath']();
}

export function GetInventory() {
  return window['go']['main']['App']['GetInventory']();
}

export function ListSkillFiles(arg1, arg2) {
  return window['go']['main']['App']['ListSkillFiles'](arg1, arg2);
}

export function OpenInTerminal(arg1) {
  return window['go']['main']['App']['OpenInTerminal'](arg1);
}

export function OpenInVSCode(arg1) {
  return window['go']['main']['App']['OpenInVSCode'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PullRepository(arg1) {
  return window['go']['main']['App']['PullRepository'](arg1);
}

export function PullSource(arg1) {
  return window['go']['main']['App']['PullSource'](arg1);
}

export function ReadSkillEnvFile(arg1) {
  return window['go']['main']['App']['ReadSkillEnvFile'](arg1);
}

export function ReadSkillFilePreview(arg1, arg2) {
  return window['go']['main']['App']['ReadSkillFilePreview'](arg1, arg2);
}

export function RemoveMissingSkill(arg1) {
  return window['go']['main']['App']['RemoveMissingSkill'](arg1);
}

export function RemoveRepository(arg1) {
  return window['go']['main']['App']['RemoveRepository'](arg1);
}

export function RemoveSource(arg1) {
  return window['go']['main']['App']['RemoveSource'](arg1);
}

export function RenameRepository(arg1, arg2) {
  return window['go']['main']['App']['RenameRepository'](arg1, arg2);
}

export function RenameSource(arg1, arg2) {
  return window['go']['main']['App']['RenameSource'](arg1, arg2);
}

export function RescanAll() {
  return window['go']['main']['App']['RescanAll']();
}

export function ResolveConflict(arg1) {
  return window['go']['main']['App']['ResolveConflict'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveLLMConfig(arg1) {
  return window['go']['main']['App']['SaveLLMConfig'](arg1);
}

export function SaveSkillEnvFile(arg1, arg2) {
  return window['go']['main']['App']['SaveSkillEnvFile'](arg1, arg2);
}

export function SaveSkillNote(arg1, arg2) {
  return window['go']['main']['App']['SaveSkillNote'](arg1, arg2);
}

export function SaveSkillTags(arg1, arg2) {
  return window['go']['main']['App']['SaveSkillTags'](arg1, arg2);
}

export function UseExistingRepository(arg1, arg2) {
  return window['go']['main']['App']['UseExistingRepository'](arg1, arg2);
}
